package:
    name: hfm
    version: 0.1.2
source:
    fn: hfm_0.1.2.tar.gz
    sha256: 0f760ffef2b882532a4b8bef64769297d6d199c01290ead5ab7e737865a625d2
    url: https://github.com/Mirebeau/HamiltonFastMarching/archive/v0.1.2.tar.gz
build:
    number: '0'
    skip: true  # [win and py<35]

requirements:
    build:
        - cmake
        - toolchain
        - gcc_linux-64 # [linux]
        - gxx_linux-64 # [linux]
        - setuptools
        - jmm_cpplibs
        - pybind11
        - numpy
    run:
        - pybind11
        - numpy

test:
    imports:
        HFMpy.HFM_Isotropic2

about:
    dev_url: https://github.com/Mirebeau/HamiltonFastMarching
    license: Licence GPU GPL v3
    license_family: GPL

extra:
    recipe-maintainers:
        - gouarin