package:
    name: hfm
    version: 0.1.3
source:
    fn: hfm_0.1.3.tar.gz
    sha256: bd6746b267d2f5ce13b551ac7b61792389930dddb02899446a038fca5e6106a7
    url: https://github.com/Mirebeau/HamiltonFastMarching/archive/v0.1.3.tar.gz
build:
  features:
    - vc14    # [win]
  number: '0'
  skip: true  # [win and py<35]

requirements:
    build:
        - vc 14        # [win and py36]
        - cmake
        - toolchain
        - gcc_linux-64 # [linux]
        - gxx_linux-64 # [linux]
        - setuptools
        - jmm_cpplibs
        - pybind11
        - numpy
    run:
        - vc 14   # [win and py36]
        - pybind11
        - numpy

test:
    imports:
        HFMpy.HFM_Isotropic2

about:
    dev_url: https://github.com/Mirebeau/HamiltonFastMarching
    license: Licence GPU GPL v3
    license_family: GPL

extra:
    recipe-maintainers:
        - gouarin